apiVersion: extensions.agents.x-k8s.io/v1beta1
kind: SandboxWarmPool
metadata:
  name: ai-agent-backend-pool
  namespace: ai-agent
spec:
  replicas: 2
  sandboxTemplateRef:
    name: ai-agent-backend-template
