apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agent

resources:
  - manifests/00-namespace.yaml
  - manifests/01-serviceaccount.yaml
  - manifests/02-rbac.yaml
  - manifests/03-configmap.yaml
  - manifests/04-postgres.yaml
  - manifests/05-backend-template.yaml
  - manifests/06-backend-warmpool.yaml
  - manifests/07-backend-claim.yaml
  - manifests/08-backend-service.yaml
  - manifests/09-frontend-deployment.yaml
  - manifests/10-frontend-service.yaml
  - manifests/11-networkpolicy.yaml

images:
  - name: docker.io/devopscube/ai-agent-backend
    newTag: v1.7.1
  - name: docker.io/devopscube/ai-agent-frontend
    newTag: v1.8.2

configMapGenerator:
  - name: ai-agent-config
    namespace: ai-agent
    behavior: merge
    options:
      disableNameSuffixHash: true
    literals:
      - AWS_REGION=us-west-2
      - DIAGNOSTICS_MODEL_ID=us.amazon.nova-pro-v1:0
      - REMEDIATION_MODEL_ID=us.amazon.nova-pro-v1:0
      - REQUIRE_APPROVAL=true
      - DIAGNOSTICS_MODEL_PRICE_INPUT_PER_1K=0.0008
      - DIAGNOSTICS_MODEL_PRICE_OUTPUT_PER_1K=0.0032
      - REMEDIATION_MODEL_PRICE_INPUT_PER_1K=0.0008
      - REMEDIATION_MODEL_PRICE_OUTPUT_PER_1K=0.0032

secretGenerator:
  - name: ai-agent-secrets
    namespace: ai-agent
    options:
      disableNameSuffixHash: true
    literals:
      - DATABASE_PASSWORD=x79BQgd2HJ16qYe0c0MaT106
  - name: ai-agent-postgres-secrets
    namespace: ai-agent
    literals:
      - POSTGRES_PASSWORD=x79BQgd2HJ16qYe0c0MaT106
